.ukGovDashComponents_js_metadata <- function() {
deps_metadata <- list(`uk_gov_dash_components` = structure(list(name = "uk_gov_dash_components",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-UkGovDashComponents.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "ukGovDashComponents",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`uk_gov_dash_components` = structure(list(name = "uk_gov_dash_components",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-UkGovDashComponents.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "ukGovDashComponents",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`uk_gov_dash_components` = structure(list(name = "uk_gov_dash_components",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'uk_gov_dash_components.min.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "ukGovDashComponents",
all_files = FALSE), class = "html_dependency"),
`uk_gov_dash_components` = structure(list(name = "uk_gov_dash_components",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'uk_gov_dash_components.min.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "ukGovDashComponents",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"))
return(deps_metadata)
}
